import { Router, type IRouter } from "express";
import healthRouter from "./health";
import aiCommentRouter from "./ai/comment";
import aiDetectRouter from "./ai/detect";
import aiHumanizeRouter from "./ai/humanize";
import aiSmartReviewRouter from "./ai/smart-review";
import aiSectionReviewRouter from "./ai/section-review";
import aiAutoReviewRouter from "./ai/auto-review";
import aiPlatformReviewRouter from "./ai/platform-review";
import aiProofreadRouter from "./ai/proofread-text";
import aiDefineRouter from "./ai/define";
import aiSummarizeRouter from "./ai/summarize";
import aiWriterRouter from "./ai/writer";
import aiChatPdfRouter from "./ai/chat-pdf";
import aiTopicsRouter from "./ai/topics";
import aiParaphraserRouter from "./ai/paraphraser";
import aiRecommendAnalysisRouter from "./ai/recommend-analysis";
import aiSlidesOutlineRouter from "./ai/slides-outline";
import aiVisionRouter from "./ai/vision";
import aiFullReviewRouter from "./ai/full-review";
import researchSearchRouter from "./research/search";
import thesisRolesRouter from "./thesis/roles";
import citationFormatRouter from "./citation/format";
import citationPlagiarismRouter from "./citation/plagiarism";

const router: IRouter = Router();

router.use(healthRouter);
router.use(aiCommentRouter);
router.use(aiDetectRouter);
router.use(aiHumanizeRouter);
router.use(aiSmartReviewRouter);
router.use(aiSectionReviewRouter);
router.use(aiAutoReviewRouter);
router.use(aiPlatformReviewRouter);
router.use(aiProofreadRouter);
router.use(aiDefineRouter);
router.use(aiSummarizeRouter);
router.use(aiWriterRouter);
router.use(aiChatPdfRouter);
router.use(aiTopicsRouter);
router.use(aiParaphraserRouter);
router.use(aiRecommendAnalysisRouter);
router.use(aiSlidesOutlineRouter);
router.use(aiVisionRouter);
router.use(aiFullReviewRouter);
router.use(researchSearchRouter);
router.use(thesisRolesRouter);
router.use(citationFormatRouter);
router.use(citationPlagiarismRouter);

export default router;
