import { useState } from "react";
import { useLanguage } from "../../lib/i18n";
import PptxGenJS from "pptxgenjs";

type Slide = { title: string; bullets: string[]; speakerNotes: string };
type Outline = { title: string; subtitle: string; slides: Slide[] };

const GOLD = "#b45309";
const NAVY = "#1e293b";

const THEMES = [
  { key: "academic", ar: "أكاديمي رصين", en: "Academic", bg: "FFFFFF", text: "1E293B", accent: "B45309", title: "0F172A" },
  { key: "modern",   ar: "حديث ملوّن",   en: "Modern",   bg: "0F172A", text: "E2E8F0", accent: "FACC15", title: "FFFFFF" },
  { key: "minimal",  ar: "بسيط نظيف",    en: "Minimal",  bg: "F8FAFC", text: "334155", accent: "0EA5E9", title: "0F172A" },
  { key: "warm",     ar: "دافئ ذهبي",    en: "Warm Gold", bg: "FFFBEB", text: "451A03", accent: "B45309", title: "78350F" },
];

export default function SlidesMaker() {
  const { lang } = useLanguage();
  const isAr = lang === "ar";

  const [topic, setTopic] = useState("");
  const [audience, setAudience] = useState("");
  const [slidesCount, setSlidesCount] = useState(10);
  const [theme, setTheme] = useState("academic");
  const [loading, setLoading] = useState(false);
  const [outline, setOutline] = useState<Outline | null>(null);
  const [error, setError] = useState("");

  const generate = async () => {
    setError(""); setOutline(null);
    if (topic.trim().length < 5) { setError(isAr ? "أدخل موضوعاً (5 أحرف على الأقل)" : "Enter a topic (5+ chars)"); return; }
    setLoading(true);
    try {
      const r = await fetch("/api/ai/slides-outline", {
        method: "POST", headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ topic, audience, slidesCount, lang }),
      });
      const data = await r.json();
      if (!r.ok) throw new Error(data.error || "Failed");
      setOutline(data);
    } catch (e) {
      setError(e instanceof Error ? e.message : (isAr ? "خطأ" : "Error"));
    } finally { setLoading(false); }
  };

  const download = async () => {
    if (!outline) return;
    const t = THEMES.find(x => x.key === theme) ?? THEMES[0];
    const pptx = new PptxGenJS();
    pptx.layout = "LAYOUT_WIDE";
    pptx.title = outline.title;

    // Cover slide
    const cover = pptx.addSlide();
    cover.background = { color: t.bg };
    cover.addShape("rect", { x: 0, y: 0, w: 13.33, h: 0.45, fill: { color: t.accent } });
    cover.addText(outline.title, {
      x: 0.6, y: 2.3, w: 12.1, h: 1.6,
      fontSize: 44, bold: true, color: t.title,
      align: isAr ? "right" : "left", valign: "middle",
      fontFace: isAr ? "Tajawal" : "Calibri",
      rtlMode: isAr,
    });
    if (outline.subtitle) {
      cover.addText(outline.subtitle, {
        x: 0.6, y: 4.0, w: 12.1, h: 0.8,
        fontSize: 22, color: t.text,
        align: isAr ? "right" : "left",
        fontFace: isAr ? "Tajawal" : "Calibri",
        rtlMode: isAr,
      });
    }
    cover.addText(isAr ? "أُنشئت بواسطة منصة محكّم" : "Generated by Muhakkim", {
      x: 0.6, y: 6.7, w: 12.1, h: 0.4,
      fontSize: 11, color: t.accent, italic: true,
      align: isAr ? "right" : "left",
      fontFace: isAr ? "Tajawal" : "Calibri",
      rtlMode: isAr,
    });

    // Content slides
    outline.slides.forEach((s, i) => {
      const slide = pptx.addSlide();
      slide.background = { color: t.bg };
      // Title bar
      slide.addShape("rect", { x: 0, y: 0, w: 13.33, h: 0.85, fill: { color: t.accent } });
      slide.addText(s.title, {
        x: 0.4, y: 0.1, w: 11.5, h: 0.7,
        fontSize: 26, bold: true, color: "FFFFFF",
        align: isAr ? "right" : "left", valign: "middle",
        fontFace: isAr ? "Tajawal" : "Calibri",
        rtlMode: isAr,
      });
      slide.addText(`${i + 1}`, {
        x: 12.3, y: 0.15, w: 0.9, h: 0.55,
        fontSize: 14, bold: true, color: "FFFFFF",
        align: "center", valign: "middle",
      });
      // Bullets
      if (s.bullets.length > 0) {
        slide.addText(
          s.bullets.map(b => ({ text: b, options: { bullet: { code: "25CF" }, breakLine: true } })),
          {
            x: 0.6, y: 1.3, w: 12.1, h: 5.5,
            fontSize: 20, color: t.text,
            align: isAr ? "right" : "left",
            valign: "top",
            paraSpaceAfter: 12,
            lineSpacingMultiple: 1.3,
            fontFace: isAr ? "Tajawal" : "Calibri",
            rtlMode: isAr,
          },
        );
      }
      // Footer
      slide.addText(outline.title, {
        x: 0.4, y: 7.05, w: 12.5, h: 0.3,
        fontSize: 9, color: t.accent, italic: true,
        align: isAr ? "right" : "left",
        fontFace: isAr ? "Tajawal" : "Calibri",
        rtlMode: isAr,
      });
      // Speaker notes
      if (s.speakerNotes) slide.addNotes(s.speakerNotes);
    });

    const safeName = (outline.title || "presentation").replace(/[^\w\u0600-\u06FF\s-]+/g, "").replace(/\s+/g, "_").slice(0, 60);
    await pptx.writeFile({ fileName: `${safeName}.pptx` });
  };

  return (
    <div dir={isAr ? "rtl" : "ltr"} style={{ padding: "20px 16px 48px", maxWidth: 960, margin: "0 auto" }}>
      {/* Header */}
      <div style={{ background: "linear-gradient(135deg,#fffbeb,#fff7ed)", border: "1.5px solid #fde68a", borderRadius: 16, padding: 20, marginBottom: 16, display: "flex", alignItems: "center", gap: 12 }}>
        <div style={{ width: 50, height: 50, borderRadius: 14, background: "linear-gradient(135deg,#C9A84C,#b45309)", display: "flex", alignItems: "center", justifyContent: "center", fontSize: 24 }}>📊</div>
        <div>
          <h2 style={{ margin: 0, fontSize: 18, fontWeight: 900, color: NAVY }}>{isAr ? "مولّد عروض البوربوينت الذكي" : "AI PowerPoint Generator"}</h2>
          <p style={{ margin: "4px 0 0", fontSize: 12.5, color: "#92400e" }}>{isAr ? "أدخل الموضوع · احصل على عرض احترافي قابل للتحميل (.pptx)" : "Enter topic · get a professional downloadable .pptx deck"}</p>
        </div>
      </div>

      {/* Form */}
      <div style={{ background: "#fff", border: "1.5px solid #e8ecf4", borderRadius: 16, padding: 20, marginBottom: 16 }}>
        <label style={{ display: "block", fontSize: 13, fontWeight: 700, color: NAVY, marginBottom: 6 }}>{isAr ? "الموضوع" : "Topic"}</label>
        <textarea value={topic} onChange={e => setTopic(e.target.value)}
          placeholder={isAr ? "مثال: أساليب القياس النفسي في البحث التربوي" : "Example: Psychometric methods in educational research"}
          style={{ width: "100%", minHeight: 80, padding: "10px 12px", borderRadius: 9, border: "1.5px solid #e2e8f0", fontSize: 14, fontFamily: "inherit", boxSizing: "border-box", resize: "vertical" }} />

        <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 12, marginTop: 14 }}>
          <div>
            <label style={{ display: "block", fontSize: 13, fontWeight: 700, color: NAVY, marginBottom: 6 }}>{isAr ? "الجمهور" : "Audience"}</label>
            <input value={audience} onChange={e => setAudience(e.target.value)}
              placeholder={isAr ? "طلاب دراسات عليا، مؤتمر..." : "Grad students, conference..."}
              style={{ width: "100%", padding: "8px 10px", borderRadius: 8, border: "1.5px solid #e2e8f0", fontSize: 13, fontFamily: "inherit", boxSizing: "border-box" }} />
          </div>
          <div>
            <label style={{ display: "block", fontSize: 13, fontWeight: 700, color: NAVY, marginBottom: 6 }}>{isAr ? `عدد الشرائح (${slidesCount})` : `Slides (${slidesCount})`}</label>
            <input type="range" min={5} max={20} step={1} value={slidesCount} onChange={e => setSlidesCount(parseInt(e.target.value))} style={{ width: "100%", accentColor: GOLD }} />
          </div>
        </div>

        <label style={{ display: "block", fontSize: 13, fontWeight: 700, color: NAVY, marginBottom: 8, marginTop: 14 }}>{isAr ? "نمط التصميم" : "Theme"}</label>
        <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fill,minmax(130px,1fr))", gap: 8 }}>
          {THEMES.map(t => {
            const active = theme === t.key;
            return (
              <button key={t.key} onClick={() => setTheme(t.key)}
                style={{ background: active ? "#fffbeb" : "#fff", border: active ? "1.5px solid #fde68a" : "1.5px solid #e8ecf4", color: active ? GOLD : NAVY, borderRadius: 10, padding: "10px 8px", fontSize: 12, fontWeight: 700, cursor: "pointer", fontFamily: "inherit", display: "flex", flexDirection: "column", alignItems: "center", gap: 6 }}>
                <span style={{ display: "flex", gap: 3 }}>
                  <span style={{ width: 14, height: 14, borderRadius: 3, background: `#${t.bg}`, border: "1px solid #cbd5e1" }} />
                  <span style={{ width: 14, height: 14, borderRadius: 3, background: `#${t.accent}` }} />
                  <span style={{ width: 14, height: 14, borderRadius: 3, background: `#${t.text}` }} />
                </span>
                <span>{isAr ? t.ar : t.en}</span>
              </button>
            );
          })}
        </div>

        <button onClick={generate} disabled={loading}
          style={{ width: "100%", marginTop: 16, background: "linear-gradient(135deg,#C9A84C,#b45309)", border: "none", borderRadius: 10, color: "#fff", padding: "12px", fontWeight: 800, fontSize: 14, cursor: loading ? "wait" : "pointer", fontFamily: "inherit", boxShadow: "0 4px 12px #C9A84C33", opacity: loading ? 0.7 : 1 }}>
          {loading ? (isAr ? "⏳ جارٍ إنشاء الهيكل..." : "⏳ Generating outline...") : (isAr ? "✨ ولّد هيكل العرض" : "✨ Generate Outline")}
        </button>
        {error && <div style={{ marginTop: 12, padding: "8px 12px", background: "#fef2f2", border: "1px solid #fecaca", color: "#dc2626", borderRadius: 8, fontSize: 13 }}>{error}</div>}
      </div>

      {/* Preview & download */}
      {outline && (
        <div style={{ background: "#fff", border: "1.5px solid #fde68a", borderRadius: 16, padding: 20 }}>
          <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between", marginBottom: 14, gap: 8, flexWrap: "wrap" }}>
            <div>
              <div style={{ fontSize: 16, fontWeight: 900, color: NAVY }}>{outline.title}</div>
              {outline.subtitle && <div style={{ fontSize: 12.5, color: "#64748b", marginTop: 2 }}>{outline.subtitle}</div>}
              <div style={{ fontSize: 11, color: GOLD, fontWeight: 700, marginTop: 4 }}>{outline.slides.length} {isAr ? "شريحة" : "slides"}</div>
            </div>
            <button onClick={download}
              style={{ background: "linear-gradient(135deg,#1e293b,#334155)", border: "none", borderRadius: 10, color: "#fff", padding: "10px 18px", fontWeight: 800, fontSize: 13, cursor: "pointer", fontFamily: "inherit", display: "flex", alignItems: "center", gap: 8 }}>
              💾 {isAr ? "تحميل PowerPoint" : "Download PowerPoint"}
            </button>
          </div>

          <div style={{ display: "flex", flexDirection: "column", gap: 10 }}>
            {outline.slides.map((s, i) => (
              <div key={i} style={{ background: "#fafbff", border: "1px solid #eef1f8", borderRadius: 10, padding: "12px 14px" }}>
                <div style={{ display: "flex", alignItems: "center", gap: 8, marginBottom: 6 }}>
                  <span style={{ background: GOLD, color: "#fff", borderRadius: 6, padding: "2px 8px", fontSize: 11, fontWeight: 900 }}>#{i + 1}</span>
                  <span style={{ fontSize: 14, fontWeight: 800, color: NAVY }}>{s.title}</span>
                </div>
                {s.bullets.length > 0 && (
                  <ul style={{ margin: "6px 0 0", paddingInlineStart: 20, fontSize: 13, lineHeight: 1.8, color: "#334155" }}>
                    {s.bullets.map((b, j) => <li key={j}>{b}</li>)}
                  </ul>
                )}
                {s.speakerNotes && (
                  <div style={{ marginTop: 8, fontSize: 11.5, color: "#64748b", background: "#fff", border: "1px dashed #e2e8f0", borderRadius: 6, padding: "6px 10px", fontStyle: "italic" }}>
                    🎙️ {s.speakerNotes}
                  </div>
                )}
              </div>
            ))}
          </div>
        </div>
      )}
    </div>
  );
}
